---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:6.1.3
  amd64: ghcr.io/hassio-addons/debian-base/amd64:6.1.3
  armv7: ghcr.io/hassio-addons/debian-base/armv7:6.1.3
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
