---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.8.2
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.8.2
  armv7: ghcr.io/hassio-addons/debian-base/armv7:7.8.2
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
